const categories = {
  clothes: [
    { key: 0, name: "لباس", value: null },
    { key: 1, name: "پلیور", value: 10 },
    { key: 2, name: "کت", value: 12 },
    { key: 2, name: "وست", value: 10 },
    { key: 3, name: "ژاکت", value: 10 },
    { key: 4, name: "کاپشن", value: 18 },
    { key: 5, name: "پالتو", value: 20 },
    { key: 6, name: "تاپ و تی شرت", value: 3 },
    { key: 7, name: "شلوار", value: 6 },
    { key: 7, name: "شلوارک", value: 4 },
    { key: 7, name: "دامن", value: 5 },
    { key: 8, name: "پیراهن زنانه", value: 5 },
    { key: 9, name: "پیراهن مردانه", value: 5 },
    { key: 10, name: "لباس زیر", value: 3 },
    { key: 10, name: "مایو", value: 5 },
    { key: 11, name: "کلاه", value: 3 },
    { key: 12, name: "شلوار جین", value: 8 },
    { key: 13, name: "اکسسوری", value: 3 },
    { key: 14, name: "کمربند", value: 4 },
    { key: 15, name: "عینک", value: 5 },
    { key: 16, name: "ساعت", value: 6 },
  ],
  shoes: [
    { key: 13, name: "کفش", value: null },
    { key: 14, name: "بوت و نیم بوت", value: 23 },
    { key: 15, name: "کفش و صندل", value: 18 },
  ],
  bags: [
    { key: 16, name: "کیف", value: null },
    { key: 17, name: "کیف بزرگ", value: 18 },
    { key: 18, name: "کیف متوسط", value: 12 },
    { key: 19, name: "کیف کوچک", value: 10 },
  ],
  cosmetics: [
    { key: 20, name: "آرایشی و بهداشتی", value: null },
    { key: 21, name: "شامپو", value: 10 },
    { key: 22, name: "نرم کننده", value: 10 },
    { key: 23, name: "ماسک مو", value: 10 },
    { key: 24, name: "لوازم آرایش", value: 3 },
    { key: 25, name: "قرص و ویتامین", value: 3 },
  ],
  sports: [
    { key: 26, name: "ورزشی", value: null },
    { key: 27, name: "اکسسوری", value: 5 },
  ],
};

export default categories;
